project:
  type: website
  output-dir: docs  # <-- This is needed for GitHub Pages

website:
  title: "anujherp.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
