project:
  type: website
  output-dir: docs  # <-- This is needed for GitHub Pages

website:
  title: "anujherp.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: sandstone
    css: bootstrap.min.css
    toc: true

editor: visual
